import { useState, useEffect, useCallback } from "react";

type Piece = {
  src: string;
  title: string;
  caption: string;
  lore: string;
};

type Pillar = {
  id: string;
  label: string;
  blurb: string;
  pieces: Piece[];
};

type BriefingItem = {
  title: string;
  body: string;
};

const BRIEFING: BriefingItem[] = [
  {
    title: "Problem",
    body: "DARPA does not need a generic assistant. It needs a local reasoning layer that still works when cloud access, identity services, or network connectivity are degraded.",
  },
  {
    title: "Scott Helmore fit",
    body: "Scott Helmore publicly presents as a public-private acquisition innovator and Chief Innovation Officer at One Nation Innovation. That suggests a focus on transition, sourcing, and pilotable capability rather than novelty alone.",
  },
  {
    title: "Why TRU fits",
    body: "TRU is a sovereign, offline-first truth-filter and reasoning system. It is scripture-grounded, provenance-preserving, private-memory gated, and designed to run locally in DDIL conditions.",
  },
  {
    title: "Outcome",
    body: "The goal is a build DARPA can inspect, test, and transition without hidden dependencies or loss of auditability.",
  },
];

const TRANSITION_CRITERIA = [
  "Runs as a single-file offline artifact",
  "No API keys required for the core contract",
  "No telemetry and no silent network dependence",
  "Public answers stay brain + scripture only",
  "Private memory stays behind gates",
  "Export, restore, and regression checks are available",
];

const PILLARS: Pillar[] = [
  {
    id: "foundation",
    label: "I · Foundation",
    blurb: "Reference architecture, control surface, and evidence boundary.",
    pieces: [
      {
        src: "/images/compass.jpeg",
        title: "Compass",
        caption: "Fixed reference point for truth-first systems.",
        lore: "The compass represents the system's external standard. In TRU, the standard is not generated by the model; it is established before routing begins and used to judge whether a response is grounded.",
      },
      {
        src: "/images/mirrordisk.jpeg",
        title: "Hexagon Shield / Mirror Disk",
        caption: "Inspectable layers for routing, validation, and recall.",
        lore: "This piece maps to the evidence path: input, route, retrieve, validate, and return. The purpose is operational transparency so an operator can see which layer handled the request and why.",
      },
      {
        src: "/images/trucoin.jpeg",
        title: "TRU Coin",
        caption: "Control surface for ownership and accountability.",
        lore: "The coin is a shorthand for operational custody. The message is simple: no hidden vendor authority, no opaque dependency chain, and no claim without provenance.",
      },
    ],
  },
  {
    id: "cruciform",
    label: "II · Core System",
    blurb: "A sovereign reasoning stack anchored to a fixed constant.",
    pieces: [
      {
        src: "/images/cruciform-ai.jpeg",
        title: "The Cruciform AI Project",
        caption: "Reasoning stack anchored to an invariant.",
        lore: "This is the core architectural claim: a system can be kept honest if it is measured against an invariant that it cannot change. That gives you constraint, discipline, and predictable output under pressure.",
      },
      {
        src: "/images/jesument-protocol.jpeg",
        title: "The Jesument Protocol 2026",
        caption: "Operating model for alignment and inspection.",
        lore: "This card captures the idea of a machine-readable operating doctrine. The useful part for acquisition is that the system's assumptions are explicit, inspectable, and testable.",
      },
      {
        src: "/images/solar-flare-prediction.jpeg",
        title: "Solar Flare Prediction — Verified",
        caption: "Measurable output with a checked result.",
        lore: "This functions as an example of constrained prediction with an observable outcome. For DARPA, the point is not the spectacle; it is that the claim can be evaluated and repeated.",
      },
    ],
  },
  {
    id: "sovereignty",
    label: "III · Sovereignty",
    blurb: "Authority boundaries, gatekeeping, and policy discipline.",
    pieces: [
      {
        src: "/images/christ-always-wins.jpeg",
        title: "The Sovereign Architect",
        caption: "One authority boundary. Every subsystem answers to it.",
        lore: "This visual encodes a strict authority hierarchy. In TRU, lower layers do not invent their own policy. They obey the governing order, which keeps the system honest about what it is allowed to answer.",
      },
    ],
  },
  {
    id: "next-science",
    label: "IV · Edge Capability",
    blurb: "Concept studies for useful capability at the edge.",
    pieces: [
      {
        src: "/images/bridgewalk.jpeg",
        title: "Project Bridge Walk",
        caption: "Edge communications without cloud dependence.",
        lore: "This is a concept for maintaining useful function across distance and delay when the network is not trustworthy. The procurement value is obvious: a capability that still works when the comms layer is the failure point.",
      },
      {
        src: "/images/plasma-portal.jpeg",
        title: "Toroidal Plasma System",
        caption: "High-energy hardware with explicit operational discipline.",
        lore: "This is a hardware concept rendered with warning labels intact. The point is not mysticism; it is containment, power discipline, and handling rules that are visible to the operator.",
      },
      {
        src: "/images/harmonic-handshake.jpeg",
        title: "Harmonic Handshake",
        caption: "Controlled state transfer between systems.",
        lore: "This piece stands in for a protocol that moves state without loss of integrity. That is the kind of handoff that matters for transition, integration, and operator trust.",
      },
      {
        src: "/images/game-art.jpeg",
        title: "Logos Intercession / Aetheric Triumph",
        caption: "System components arranged for review.",
        lore: "A compact board of parts, each with a role. For acquisition audiences, the useful feature is that the components are legible and can be discussed individually rather than as a blur of claims.",
      },
      {
        src: "/images/fusion-magnets.jpeg",
        title: "AI-Native HTS Magnet Acceleration",
        caption: "R&D acceleration with a measurable target.",
        lore: "This is the most procurement-friendly of the science studies: use AI to shorten design cycles, reduce cost, and move a magnet programme from concept to testable progress.",
      },
      {
        src: "/images/heat-teg.jpeg",
        title: "Thermoelectric Generator",
        caption: "Power extraction with explicit limits.",
        lore: "A disciplined energy concept: generate useful output, but do not pretend the source is free or the constraints do not matter. Operational discipline is part of the design.",
      },
    ],
  },
];

const ALL: Piece[] = PILLARS.flatMap((p) => p.pieces);

export default function TruVision() {
  const [index, setIndex] = useState<number | null>(null);
  const active = index == null ? null : ALL[index];

  const close = useCallback(() => setIndex(null), []);
  const prev = useCallback(
    () => setIndex((i) => (i == null ? i : (i - 1 + ALL.length) % ALL.length)),
    []
  );
  const next = useCallback(
    () => setIndex((i) => (i == null ? i : (i + 1) % ALL.length)),
    []
  );

  useEffect(() => {
    if (index == null) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") close();
      else if (e.key === "ArrowLeft") prev();
      else if (e.key === "ArrowRight") next();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [index, close, prev, next]);

  return (
    <div className="min-h-screen bg-black text-white font-mono antialiased">
      <div className="mx-auto max-w-5xl px-6 py-16 sm:py-24">
        <div className="mb-16">
          <div className="flex items-center justify-between text-[10px] uppercase tracking-[0.3em] text-neutral-600">
            <span>TRU · Vision / Procurement brief</span>
            <a href="/" className="hover:text-neutral-300 transition-colors">
              ← back
            </a>
          </div>

          <h1 className="mt-10 text-3xl sm:text-5xl font-light leading-[1.1] tracking-tight">
            Truth is Constant.
            <br />
            <span className="text-neutral-500">Perspective is Fluid.</span>
          </h1>

          <p className="mt-6 max-w-2xl text-sm text-neutral-500 leading-relaxed">
            Prepared for the 29 July DARPAConnect conversation with Scott
            Helmore. This version is written for acquisition and transition: it
            frames TRU as a testable, offline-capable reasoning layer for DDIL
            conditions, with clear evaluation boundaries and no hidden cloud
            dependency.
          </p>

          <div className="mt-8 max-w-2xl border border-neutral-900 bg-neutral-950/80 p-5">
            <div className="text-[10px] uppercase tracking-[0.3em] text-neutral-500">
              What this page is for
            </div>
            <p className="mt-3 text-[13px] text-neutral-400 leading-relaxed">
              It is a procurement conversation aid: short, inspectable, and
              focused on transition readiness. The aim is to make the capability
              legible to a public-private acquisition audience and to show how
              TRU fits a pilot, evaluation, and transition path.
            </p>
          </div>

          <div className="mt-6 inline-flex flex-wrap gap-2 text-[10px] uppercase tracking-[0.25em] text-neutral-600">
            <span className="rounded-full border border-neutral-800 px-3 py-1">offline-first</span>
            <span className="rounded-full border border-neutral-800 px-3 py-1">no telemetry</span>
            <span className="rounded-full border border-neutral-800 px-3 py-1">local authority</span>
            <span className="rounded-full border border-neutral-800 px-3 py-1">provenance-preserving</span>
            <span className="rounded-full border border-neutral-800 px-3 py-1">DDIL-ready</span>
          </div>

          <div className="mt-10 grid gap-4 sm:grid-cols-2">
            {BRIEFING.map((item) => (
              <div key={item.title} className="border border-neutral-900 bg-neutral-950/70 p-5">
                <div className="text-[10px] uppercase tracking-[0.3em] text-neutral-500">
                  {item.title}
                </div>
                <p className="mt-3 text-[13px] text-neutral-400 leading-relaxed">
                  {item.body}
                </p>
              </div>
            ))}
          </div>

          <div className="mt-10 border border-neutral-900 bg-neutral-950/70 p-5 max-w-2xl">
            <div className="text-[10px] uppercase tracking-[0.3em] text-neutral-500">
              Transition criteria
            </div>
            <ul className="mt-4 grid gap-2 text-[13px] text-neutral-400 leading-relaxed sm:grid-cols-2">
              {TRANSITION_CRITERIA.map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="text-neutral-600">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="space-y-24">
          {PILLARS.map((pillar) => (
            <section key={pillar.id} id={pillar.id}>
              <div className="border-l border-neutral-800 pl-6 mb-10">
                <div className="text-[10px] uppercase tracking-[0.3em] text-neutral-600">
                  {pillar.label}
                </div>
                <p className="mt-3 text-sm text-neutral-400 leading-relaxed max-w-2xl">
                  {pillar.blurb}
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
                {pillar.pieces.map((piece) => {
                  const flatIndex = ALL.indexOf(piece);
                  return (
                    <button
                      key={piece.src}
                      onClick={() => setIndex(flatIndex)}
                      className="group text-left"
                    >
                      <div className="relative overflow-hidden border border-neutral-900 group-hover:border-neutral-500 transition-colors">
                        <img
                          src={piece.src}
                          alt={piece.title}
                          loading="lazy"
                          className="w-full aspect-square object-cover opacity-80 group-hover:opacity-100 transition-opacity duration-500"
                        />
                        <div className="absolute top-2 right-2 text-[9px] uppercase tracking-[0.2em] text-neutral-500 opacity-0 group-hover:opacity-100 transition-opacity">
                          ↗ view
                        </div>
                      </div>
                      <div className="mt-3 text-xs text-neutral-300 group-hover:text-white transition-colors">
                        {piece.title}
                      </div>
                      <div className="mt-1 text-[11px] text-neutral-600 leading-relaxed">
                        {piece.caption}
                      </div>
                    </button>
                  );
                })}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-32 pt-8 border-t border-neutral-900 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-6">
          <div className="text-[10px] uppercase tracking-[0.3em] text-neutral-700">
            Prepared for Scott Helmore · 29 July · DARPAConnect
          </div>
          <div className="flex gap-6">
            <a
              href="/whitepaper"
              className="text-[10px] uppercase tracking-[0.3em] text-neutral-700 hover:text-white transition-colors"
            >
              read the whitepaper →
            </a>
            <a
              href="/sovereign"
              className="text-[10px] uppercase tracking-[0.3em] text-neutral-700 hover:text-white transition-colors"
            >
              open sovereign console →
            </a>
          </div>
        </div>
      </div>

      {active && (
        <div
          onClick={close}
          className="fixed inset-0 z-50 bg-black/90 backdrop-blur-sm flex items-center justify-center p-6 cursor-zoom-out"
        >
          <div className="max-w-3xl w-full" onClick={(e) => e.stopPropagation()}>
            <img
              src={active.src}
              alt={active.title}
              className="w-full max-h-[72vh] object-contain border border-neutral-800"
            />
            <div className="mt-4 flex items-baseline justify-between gap-4">
              <div className="min-w-0">
                <div className="text-sm text-neutral-200">{active.title}</div>
                <div className="mt-2 text-[12px] text-neutral-400 leading-relaxed max-w-xl">
                  {active.lore}
                </div>
              </div>
              <button
                onClick={close}
                className="shrink-0 text-[10px] uppercase tracking-[0.3em] text-neutral-600 hover:text-white transition-colors"
              >
                close ✕
              </button>
            </div>

            <div className="mt-6 flex items-center justify-between border-t border-neutral-900 pt-4">
              <button
                onClick={prev}
                className="text-[10px] uppercase tracking-[0.3em] text-neutral-600 hover:text-white transition-colors"
              >
                ← prev
              </button>
              <div className="text-[10px] uppercase tracking-[0.3em] text-neutral-700">
                {index! + 1} / {ALL.length}
              </div>
              <button
                onClick={next}
                className="text-[10px] uppercase tracking-[0.3em] text-neutral-600 hover:text-white transition-colors"
              >
                next →
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
